package enums;

public enum TipoSolicitacao {
    SOLICITACAO_BURACAO,
    SOLICITACAO_PODA,
    SOLICITACAO_ARVORE_CAIDA,
    SOLICITACAO_REFORMA,
    SOLICITACAO_ASSEDIO,
    SOLICITACAO_ILUMINACAO
}
